# Generated by Django 3.0 on 2022-03-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_auto_20220322_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/Profile_Pics'),
        ),
    ]
